apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdeploy-hsn-hello1
spec:
  replicas : 3
  selector:
    matchLabels:
      app: devopsdeploy-hsn-hello1
  template:
    metadata:
      labels:
        app: devopsdeploy-hsn-hello1
    spec:
      containers:
      - name: devopsdeploy-hsn-hello1
        image: hsntpl/demodevops-v104
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
