apiVersion: v1
kind: Pod
metadata:
  name: devops-hsn02-hello
  labels:
    app.kubernetes.io/name: devops-hsn02-hello
    hsn-type: backend
    hsn-app: hello-modul
    hsn-project-name: hello-hsn02
spec:
  containers:
  - name: devops-hsn02-hello
    image: hsntpl/demodevops-v104
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
